---
 - hosts: localhost
   connection: local
   gather_facts: false
   user: root
   pre_tasks:
    - include_vars: ec2_vars/{{type}}.yml
   roles:
    - provision-ec2 

- hosts: dev03.moneylion.com
   gather_facts: true
   user: root
   roles:
    - common
