---
 - name: Gather EC2 Facts
   action: ec2_facts
  
 - name: Set Hostname according to hosts inventory
   template: src=hostname.j2 dest=/etc/hostname
   when: set_hostname is defined
   notify: set hostname

 # This ensures that there's a line in the file /etc/hosts to describe the new hostname.
 - name: Ensure self-reference hostname in /etc/hosts
   lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1' line="127.0.0.1 localhost {{ set_hostname }}" owner=root group=root mode=0644
   when: set_hostname is defined

 - name: Regenerate apt-cache
   apt: update_cache=yes

 - name: install python-software-properties
   apt: pkg=python-software-properties state=installed

 - name: install default packages
   apt: pkg={{ item }} state=installed
   with_items:
     - git
