ec2_keypair: ""
ec2_security_group: "sg-24d72b41"
ec2_instance_type: "t2.medium"
ec2_image: "ami-2c6e7e42"
ec2_subnet_ids: ['subnet-dacc2dad']
ec2_region: "ap-northeast-1"
ec2_tag_Name: "dev03.moneylion.com"
ec2_tag_Type: "webserver"
ec2_tag_Environment: "development"
ec2_volume_size: 16
