---
- name: Adding sites config
  template:
    src: nginx_config/sites.example.j2
    dest: /etc/nginx/sites-available/{{ec2_tag_Name}}
    owner: root
    group: root
    mode: 0644
  notify: nginx restart


- name: Creating symlinks
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: symlinks

- name: ensure nginx is enabled and running
  service: name=nginx enabled=yes state=running
